namespace: rhpds
name: ansible_automation_platform
version: 1.0.0
readme: README.md
authors:
- Mitesh The Mouse <mitsharm@redhat.com>
description: your collection description
license:
- GPL-2.0-or-later
license_file: ''
tags: []
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore: []
