---

# ---------------------------------------------------------
# The following variables should not be defined in AgnosticV
# due to the use of the !unsafe filter.
# ---------------------------------------------------------

controller_credential_types:
  - name: "kubeconfig"
    inputs:
      fields:
        - type: string
          id: kube_config
          label: kubeconfig
          secret: true
          multiline: true
    injectors:
      env:
        K8S_AUTH_KUBECONFIG: !unsafe "{{ tower.filename.kubeconfig }}"
      file:
        template.kubeconfig: !unsafe "{{ kube_config }}"

  - name: Satellite_Collection
    description: Credential for redhat.satellite collection
    inputs:
      fields:
        - id: username
          type: string
          label: Satellite Username
        - id: password
          type: string
          label: Satellite Password
          secret: true
        - id: host
          type: string
          label: Satellite Hostname
      required:
        - username
        - password
        - host
    injectors:
      env:
        SATELLITE_PASSWORD: !unsafe '{{ password }}'
        SATELLITE_USERNAME: !unsafe '{{ username }}'
        SATELLITE_SERVER_URL: !unsafe '{{ host }}'
        SATELLITE_VALIDATE_CERTS: 'false'

  - name: GitHub_Personal_Access_Token
    description: Credential for GitHub repo operations automation
    inputs:
      fields:
        - id: personal_access_token
          type: string
          label: Personal Access Token
          secret: true
          help_text: GitHub Personal Access Token
          multiline: true
      required:
        - personal_access_token
    injectors:
      env:
        MY_PA_TOKEN: !unsafe '{{ personal_access_token }}'

  - name: Splunk HEC Token
    description: Credential to send event data to a Splunk deployment
    kind: cloud
    inputs:
      fields:
        - type: string
          id: splunk_url
          label: Splunk URL
          help_text: URL of the Splunk HTTP Event Collector
        - type: string
          id: splunk_index
          label: Splunk Index
          help_text: Splunk index to which events will be collected
        - type: string
          id: splunk_hectoken
          label: Splunk HEC Token
          secret: true
          help_text: HTTP Event Collector tokens used for Splunk platform authentication
      required:
        - splunk_url
        - splunk_index
        - splunk_hectoken
    injectors:
      extra_vars:
        splunk_url: !unsafe '{{ splunk_url }}'
        splunk_index: !unsafe '{{ splunk_index }}'
        splunk_hectoken: !unsafe '{{ splunk_hectoken }}'

  - name: Product Demos Bootstrap Credential
    description: Custom credential type for bootstrapping Ansible Product Demos
    inputs:
      fields:
        - id: host
          type: string
          label: Red Hat Ansible Automation Platform URL
        - id: username
          type: string
          label: Username
        - id: password
          type: string
          label: Password
          secret: true
        - id: oauth_token
          type: string
          label: OAuth Token
          secret: true
        - id: verify_ssl
          type: boolean
          label: Verify SSL
      required:
        - host
    injectors:
      env:
        TOWER_HOST: !unsafe '{{host}}'
        TOWER_USERNAME: !unsafe '{{username}}'
        TOWER_PASSWORD: !unsafe '{{password}}'
        TOWER_VERIFY_SSL: !unsafe '{{verify_ssl}}'
        TOWER_OAUTH_TOKEN: !unsafe '{{oauth_token}}'
        CONTROLLER_HOST: !unsafe '{{host}}'
        CONTROLLER_USERNAME: !unsafe '{{username}}'
        CONTROLLER_PASSWORD: !unsafe '{{password}}'
        CONTROLLER_VERIFY_SSL: !unsafe '{{verify_ssl}}'
        CONTROLLER_OAUTH_TOKEN: !unsafe '{{oauth_token}}'
        GATEWAY_HOSTNAME: !unsafe '{{host}}'
        GATEWAY_USERNAME: !unsafe '{{username}}'
        GATEWAY_PASSWORD: !unsafe '{{password}}'
        GATEWAY_VERIFY_SSL: !unsafe '{{verify_ssl}}'
        GATEWAY_OAUTH_TOKEN: !unsafe '{{oauth_token}}'
